<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>zulip_cs_cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\zulip-cs-lib\zulip-cs-lib.csproj" />
  </ItemGroup>

</Project>
