<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props" />

  <PropertyGroup>
    <RootNamespace>zulip_cs_lib</RootNamespace>
    <PackageTags>Zulip;CSharp;Library;</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/GinoCanessa/zulip-cs</PackageProjectUrl>
  </PropertyGroup>
  
</Project>
