name: Publish dotnet library to NuGet.org
# Basics from https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/github-actions
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Tests']
    types: [completed]
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            10.0
            9.0
            8.0

    - name: Build and Publish
      run: |
        dotnet restore src/zulip-cs-lib/zulip-cs-lib.csproj
        dotnet pack -c Release ./src/zulip-cs-lib/zulip-cs-lib.csproj -o ./nupkg
        dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GINOC_NUGET }} --source https://api.nuget.org/v3/index.json
